version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"

    # Keep only 5 open PRs at a time
    open-pull-requests-limit: 5

    # Leave ignore empty if not ignoring dependencies
    ignore: []
