name: Bug report
description: Create a report to help us improve
labels: bug
body:
  - type: textarea
    attributes:
      label: Description
      description: Describe the bug clearly and concisely
      placeholder: What's the bug? What did you expect to happen?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Screenshots (Optional)
      description: Add screenshots if applicable
      placeholder: Drag and drop images here