name: Feature request
description: Suggest an idea for this project
labels: enhancement
body:
  - type: textarea
    attributes:
      label: Description
      description: Describe your feature idea clearly
      placeholder: What feature would you like to see? How would it improve the project?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Screenshots (Optional)
      description: Add mockups or reference images if applicable
      placeholder: Drag and drop images here