name: 📝 Create an Issue
description: Report a bug, request a feature, or suggest an improvement
body:
  - type: markdown
    attributes:
      value: 

  - type: textarea
    attributes:
      label: 📋 Description
      description: Clearly describe what you want to report or suggest

    validations:
      required: true
  
  - type: textarea
    attributes:
      label: 📸 Screenshots (Optional)
      description: Add screenshots, mockups, or error messages if applicable
      placeholder: Drag and drop images here